# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'CA-PIN_IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'NMapsMap'
  pod 'RxCocoa', '6.2.0'
  pod 'Moya', '~> 15.0'
  pod 'Moya/RxSwift', '~> 15.0'
  # Pods for CA-PIN_IOS

  target 'CA-PIN_IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CA-PIN_IOSUITests' do
    # Pods for testing
  end

end
